name: Gutenbuild
description: 'Build your WordPress Gutenberg block.'
inputs:
    src:
        description: 'Directory of src files'
        required: true
        default: './src/'

    output_path:
        description: 'Directory to store built files'
        required: false
        default: './build'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.src }}
        - --output-path=${{ inputs.output_path }}
