on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Testing out the build
        steps:
        - uses: actions/checkout@v2

        - name: Gutenbuild
          id: gutenbuild
          uses: beaucollins/gutenbuild@master
          with:
            src: 'example/src'
            output_path: 'example/build'

        - name: wut
          run: find .

        - uses: actions/upload-artifact@v1
          with:
            name: 'build'
            path: 'example/build'

