on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Gutenbuild
        steps:
        - uses: actions/checkout@v2

        - uses: beaucollins/gutenbuild@master
          with:
            src: 'example/src'
            output_path: 'example/build'

        - uses: actions/upload-artifact@v1
          with:
            name: 'build'
            path: 'example/build'

